
services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: globallogix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: egor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - global-logix-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

    networks:
      - global-logix-network
  kafka:
    image: 'apache/kafka:3.7.0'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

    networks:
      - global-logix-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 2000ms
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
    networks:
      - global-logix-network

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - global-logix-network

  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_MAIL_USERNAME: ${MAILRU_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAILRU_APP_PASSWORD}
      SPRING_MAIL_HOST: smtp.mail.ru
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: "5000"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: "5000"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: "5000"
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 5000ms
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - global-logix-network

  chat-service:
    build: ./chat-service
    container_name: chat-service
    ports:
      - "8087:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - global-logix-network

  flight-service:
    build: ./flight-service
    container_name: flight-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - global-logix-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway

    ports:
      - "8080:8080"
#    depends_on:
#      - auth-service
#      - delivery-service
#      - flight-service
    networks:
      - global-logix-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - global-logix-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    networks:
      - global-logix-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - global-logix-network

volumes:
  postgres_data:


networks:
  global-logix-network:
    driver: bridge
    name: friendlivery-dev-network