name: global-logix-platform

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: globallogix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: egor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - global-logix-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - global-logix-network
  kafka:
    image: 'bitnamilegacy/kafka:4.0.0-debian-12-r10'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_NUM_PARTITIONS=3
    networks:
      - global-logix-network
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 2000ms
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
    networks:
      - global-logix-network

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
    networks:
      - global-logix-network

  flight-service:
    build: ./flight-service
    container_name: flight-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis

    networks:
      - global-logix-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - delivery-service
      - flight-service
    networks:
      - global-logix-network

volumes:
  postgres_data:

networks:
  global-logix-network:
    driver: bridge