name: global-logix-platform

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: globallogix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: egor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - global-logix-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - global-logix-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
    networks:
      - global-logix-network

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
    networks:
      - global-logix-network

  flight-service:
    build: ./flight-service
    container_name: flight-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis

    networks:
      - global-logix-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - delivery-service
      - flight-service
    networks:
      - global-logix-network

volumes:
  postgres_data:

networks:
  global-logix-network:
    driver: bridge