server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/
        - id: delivery-service
          uri: http://delivery-service:8080
          predicates:
            - Path=/api/deliveries/

        - id: flight-service
          uri: http://flight-service:8080
          predicates:
            - Path=/api/couriers/**

  redis:
    host: redis-cache
    port: 6379
    timeout: 2000ms

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
# need to remove secret from yml to env jwt.secret=${JWT_SECRET}
jwt:
  secret: "6b7980775a487f559c565790bb802aade984b7c1da40f605b34a5d2abba5fb26"
  expiration: 3600000
  refresh:
    expiration:
      604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes