global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'api-gateway'

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080']
        labels:
          application: 'auth-service'

  - job_name: 'delivery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['delivery-service:8080']
        labels:
          application: 'delivery-service'

#  - job_name: 'chat-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'chat-service:8080' ]
#        labels:
#          application: 'chat-service'
#
#  - job_name: 'flight-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'flight-service:8080' ]
#        labels:
#          application: 'flight-service'
#
#  - job_name: 'notifications-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'notifications-service:8080' ]
#        labels:
#          application: 'notifications-service'
#
#  - job_name: 'payment-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'payment-service:8080' ]
#        labels:
#          application: 'payment-service'